### ISSUE TITLE
[FR] Editable Colors

### ISSUE THREAD

**Issue by Glint-Eye** [mgmeyers/obsidian-list-callouts#10]
This plugin is really great.
I rarely use regular callouts as i find them to disruptive for most contexts. The implementation through simple one character indicators at the start of a list is really clever.

It would be great though if the colors could be customized, as I find them a little bit faint.

Cheers and great work.

**Comment by ndharari** [comment]
This would be great! Also, maybe don't show the list marker when the callout is applied (maybe should write it on a different FR?)
Anywhow, love your work!!

**Comment by adiac** [comment]
I figured out how to change colors, by editing the `data.json` file of the plugin.

**Here is how to do it:**
+ Go to the plugin folder (`your-obsidian-vault-folder\.obsidian\plugins\obsidian-list-callouts`)
+ There open the 'data.json' file
+ You see color and char(s) combinations. (and if set also the icon)
  + You can edit all of them however you like, tho the chars and icons are editable already from the plugin settings.
  + The colors are saved in an RGB pattern. (red/green/blue values)
  + The color set here is for the char(s)/icon. The list callout background will be adjusted automatically
  + Adding any additional pairs **does not work** (at the time of writing)
+ Save the file
+ Restart Obsidian (If you don't do this, the plugin will just overwrite the file, when changing plugin settings)
+ Beautiful custom colors

It is recommended that you backup the edited `data.json` file, in case an update of the plugin overwrites it.

**Comment by mgmeyers** [comment]
While you can edit the colors of the default callouts, in the latest version of this plugin you can now define your own callouts including the color
