### ISSUE TITLE
Obsidian 16.2 Reading mode

### ISSUE THREAD

**Issue by berot3** [mgmeyers/obsidian-list-callouts#17]
First, thanks a lot for this great plugin! It's exactly what I was looking for!

But, it's not working for me in reading mode.

**Live preview mode:**
<img width="735" alt="image" src="https://user-images.githubusercontent.com/52616/190086244-354e2636-472f-4805-a03b-139bca0adf63.png">

---

**Reading mode:**
<img width="757" alt="image" src="https://user-images.githubusercontent.com/52616/190086384-5e68d6dc-c39f-481f-a342-804d824d98b1.png">

**Comment by berot3** [comment]
Additionally: the set-icon-button in the settings also doesn't do anything anymore.

It all worked before the upgrade to 0.16 btw.

**Comment by menagerie198** [comment]
Obsidian 0.16.3 here, 1.0.6 List Callouts.
The icons are working again for me, but the 'Reading View' issue remains.

**Comment by Solarrixs** [comment]
Same for me as well, Obsidian v1.0.0.

**Comment by darkmarcos** [comment]
Same bug here, Obsidian v1.0.0.

**Comment by mgmeyers** [comment]
This should be fixed now. Let me know if you still have issues.

**Comment by loredonrj** [comment]
Hi, thanks for that awsome plugin. I am on Obsidian v1.1.16 (Windows 10). For me, in order for the callout to work in the "Reading" mode I needed to turn on the editor's "Live Preview" mode.
