### ISSUE TITLE
No effect in preview mode

### ISSUE THREAD

**Issue by chenxin0397** [mgmeyers/obsidian-list-callouts#2]
Thanks for the plugin, I really like it!
Looking forward to it functioning in preview mode without affecting the generated PDF document

**Comment by chenxin0397** [comment]
Sorry, I tested again, it's not that the preview mode doesn't work, it's just that the custom icons don't work in preview mode

**Comment by micwaab** [comment]
I'm having this same issue.

**Comment by chenxin0397** [comment]
Hello, I am using version 1.0.1, thanks for the update
Currently the effect of this plugin is invisible in OB's real-time reading mode. Can you handle it?
In addition, I also think there is a line break problem,I want to be able to separate two lists with blank lines
![202108161359350001001](https://user-images.githubusercontent.com/73974352/174482391-c708339e-1d35-4b97-88c3-ef82882eccc8.gif)

**Comment by mgmeyers** [comment]
This should be fixed now @chenxin0397. Let me know if you run into any additional issues
