### ISSUE TITLE
[Feature Request] Ability Add Additional Callouts

### ISSUE THREAD

**Issue by overkill864** [mgmeyers/obsidian-list-callouts#27]
I would love if we could add the ability to add more callouts and possibly https://lucide.dev/ icons instead. I don't mind if I reuse colors and such, having more callout options is the most important thing. Selecting more colors would be a plus as well, possibly even having a transparent one to just showcase an icon in front of the content. I imagine it could work similar to how you can add 'New Rules' in the plugin 'Auto Note Mover' 
<img width="794" alt="CleanShot 2022-12-27 at 09 35 19@2x" src="https://user-images.githubusercontent.com/119825814/209701881-578959f8-ba96-4b55-a7ed-d3e59a6068ca.png">

My use case: This plugin works fantastically for a sort of advanced bullet journaling. Right now I use tags like `#bookmark` as the callout character which is amazing because it does two things: 1. It hides the tag from view and 2. It Puts the bookmark icon in its place. 
<img width="742" alt="CleanShot 2022-12-27 at 09 35 58@2x" src="https://user-images.githubusercontent.com/119825814/209701963-27ec2248-ef18-4a0a-b80e-1ee76c43b61a.png">

Being able to add more callouts with more tags would allow a much more visually organized system while still being completely searchable via tags. 
Either way, love this plugin! Thanks for making it!

**Comment by img1873** [comment]
Same! This would be a really helpful function.

**Comment by lukthony** [comment]
Wanted to bump this and express interest in this feature—not sure how logistically difficult it'll be to implement, but being able to add extra list callouts would be *the* feature that would make the largest difference for my usage.

**Comment by menagerie198** [comment]
Upvote from me too. This would make your plugin much more useful for me.

**Comment by adiac** [comment]
I figured how to do this, by making a small edit/hack to the plugins main.js file. It's not fancy and definitly not a replacement for a nicer implementation, but for me I wanted to have this right away, for my system of list callouts.

**Here is how to do it:**
+ Go to the plugin folder (`your-obsidian-vault-folder\.obsidian\plugins\obsidian-list-callouts`)
+ There open the `main.js` file
+ Search for the line `var DEFAULT_SETTINGS = [`
+ Add additional list callouts in this javascript array. (example below)
  + You can also alter the colors here or edit the default list callouts in any way you like.
+ Save the file
+ Restart Obsidian
+ Beautiful additional list callouts

**Example of the edited section:**
```
var DEFAULT_SETTINGS = [
  {
    color: "255, 214, 0",
    char: "&"
  },
  {
    color: "255, 145, 0",
    char: "?"
  },
  {
    color: "255, 23, 68",
    char: "!"
  },
  {
    color: "124, 77, 255",
    char: "~"
  },
  {
    color: "0, 184, 212",
    char: "@"
  },
  {
    color: "0, 200, 83",
    char: "$"
  },
  {
    color: "158, 158, 158",
    char: "%"
  },
  {
    color: "255, 0, 255",
    char: "="
  }
];
```

It is recommended that you backup the edits you make, in case an update of the plugin overwrites them.

**Comment by menagerie198** [comment]
Coolio! Thanks for posting this. I was after more/different icon as well -- but you inspired me to go poking around the `main.js`, and I found that simply adding the name of a Lucide icon to the list beginning at line 84, I was able to supplement the icon list. + happy bunny!

**Comment by adiac** [comment]
Your're welcome. You actually don't have to add the icon to that list to use it. I configured everything in the `data.json`. Setting the icon there will work as well, even if it is not defined as usable icon.

**Comment by mgmeyers** [comment]
Hey all, thanks to eth-p you can now add additional callout definitions in the latest version
