### ISSUE TITLE
Plugin does not appear to have settings

### ISSUE THREAD

**Issue by j-maffe** [mgmeyers/obsidian-list-callouts#32]
Hello! I installed this plugin and tried it out but I didn't notice any change. I noticed from the discussions here that there is supposed to be configurable settings for the plugin. However, Obsidian doesn't show the plugin in the list on the left and doesn't have the gear icon for settings for the plugin in the Community Plugins window. The Style Settings does detect the plugin though. I tried this on a vanilla vault with no plugins and still had the same issue.
Any idea as to why this could be happening?

**Comment by j-maffe** [comment]
I just manually removed the files from the .plugins folder and downloaded the previous version release 1.0.12 and the settings were there and now it works. not sure what was wrong with 1.1.0. Let me know if you want me to try to replicate it with you.

**Comment by mgmeyers** [comment]
@j-maffe I think I found the problem. Try updating to 1.1.1 and see if that fixes it for you

**Comment by j-maffe** [comment]
Yep, it works now! thanks a lot :D
