### ISSUE TITLE
[Feature Request] Searching icons

### ISSUE THREAD

**Issue by Elec0** [mgmeyers/obsidian-list-callouts#37]
It is time-consuming and frustrating to have to go manually searching through the icon list. Particularly when you _know_ the name of the icon you already want to use.
![image](https://github.com/mgmeyers/obsidian-list-callouts/assets/5119098/b3b93bc6-618f-47cb-b562-e12431c53f76)

It would make things much easier if we could filter/search the icon list.

**Comment by FeralFlora** [comment]
Yeah, this would make the setup much more accessible!

**Comment by berot3** [comment]
its crazy how such simple things can make life much easier 😆  I waited for this search-box way tooo long 👍  Thanks!
