### ISSUE TITLE
any way to reset icons? I set an icon but I want to know use the symbol instead

### ISSUE THREAD

**Issue by almita** [mgmeyers/obsidian-list-callouts#39]
What title says. I had a '?' as a symbol but I set an icon from the list and now I want to remove the icon so that the '?' shows. 

<img width="525" alt="image" src="https://github.com/mgmeyers/obsidian-list-callouts/assets/47606562/f95471f5-f4ae-4292-9526-36f166190e72">

**Comment by acook** [comment]
You may need to delete the entry to reset the icon to the symbol, it won't hurt any of your notes.

There are also some nice question mark icons that could be used.
