### ISSUE TITLE
List Callout Styling Not Displaying in Reading Mode for Checkbox Lists

### ISSUE THREAD

**Issue by AlderKirkwall** [mgmeyers/obsidian-list-callouts#51]
# List Callout Styling Not Displaying in Reading Mode for Checkbox Lists
List callout styling for checkboxes is not visible in reading mode, but is working as expected in live preview.

## View in Live Preview Mode
![image](https://github.com/mgmeyers/obsidian-list-callouts/assets/51897451/5b00a0b5-30f3-4516-8739-cd8a8dfbc2b3)

## View in Reading Mode
![image](https://github.com/mgmeyers/obsidian-list-callouts/assets/51897451/3f44b889-0dfb-43b1-91ab-e6660001114a)

**Comment by siebentod** [comment]
+++ Very upsetting that it doesn't work with Tasks plugin

**Comment by AndriiPetrovDev** [comment]
yes, I need to highlight my tasks somehow)
