### ISSUE TITLE
Failed trying to install List Callouts 

### ISSUE THREAD

**Issue by gabrielcarus** [mgmeyers/obsidian-list-callouts#6]
I tried updating the List Callouts plugin and didn't work, so I tried to delete and install again, but it failed as well.
Tried restarting Obsidian and the error persisted. 
(Btw, nice plugin, very useful) 

![image](https://user-images.githubusercontent.com/105552060/179282243-489ba671-8429-4028-90ed-879cf9061ec8.png)

**Comment by mgmeyers** [comment]
Apologies @gabrielcarus Should be fixed now

**Comment by gabrielcarus** [comment]
thanks a lot @mgmeyers, fr, great job with the plugins, keep up the good work
