### ISSUE TITLE
Need more contrast/brightness in dark mode

### ISSUE THREAD

**Issue by Chriswaterguy** [mgmeyers/obsidian-list-callouts#64]
The highlight for the callout line looks good in light mode, but it's barely visible in light mode. (Tested in Android with an AMOLED screen, and Windows 10 on a Microsoft Surface). 

Either adjustable or a significantly increased contrast or brightness of the highlight would improve this. 

(I'm the meantime I'm just relying on the bright icon/letter at the start of the line.)

**Comment by mgmeyers** [comment]
@Chriswaterguy I've bumped up the contrast a little in dark mode. I've also added a setting in style settings to control the opacity of the background in both light/dark modes

**Comment by Chriswaterguy** [comment]
Beautiful, thank you! 

(I've bumped mine to 0.4 for light theme and 0.5 for dark theme – the colours stand out very strongly now, which is how I like it.)
