### ISSUE TITLE
[BUG] Any line break in list would break effect

### ISSUE THREAD

**Issue by mrpurplecloud** [mgmeyers/obsidian-list-callouts#8]
If there's any blank line between list items, the visual effect of list callouts would be all gone

**Comment by mgmeyers** [comment]
Thanks @mrpurplecloud This should be fixed now

**Comment by mrpurplecloud** [comment]
Thanks. However I failed to upgrade to the latest version. Does it have dependency on Obsidian 0.15.x? I'm still on the latest 0.14 stable release, maybe that's why
